### PR TITLE
Update scorecard.py

### PR DESCRIPTION
**Pull request by isokaze04**
here getting the indices, the metric for missing and special value should be consistent with the input. otherwise scores are not correctly computed.

### CODE REVIEW

**Review by guillermo-navas-palencia — COMMENTED** [review]
This is not correct. In this case, the binning process uses ``metric=indices`` in  ``transform`` to obtain the bin indexes for each variable. Then, these indexes are used to compute the score. Conclusion: this is for internal purposes, and the user inputs are disregarded. Have a look at the line: 388.

**Comment by isokaze04** [comment]
I did some manual tests (summing up bin scores from scorecard table) and find that results are different from what scorecard.score outputs.  It is caused by missing values are denoted zero however the scorecard is fit using metric_missing = "empirical".

**Comment by guillermo-navas-palencia** [comment]
Not sure. Have a look at https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/transformations.py#L195. The default value for metric_missing is 0. In case metric="indices", the last position is assigned to the missing bin. Perhaps you can share a reproducible example to clarify.

**Comment by isokaze04** [comment]
https://gist.github.com/isokaze04/81ace98a8f027c73f8f84b1453fc194f

the test I conduct, not sure whether it is something wrong with my code.

**Comment by guillermo-navas-palencia** [comment]
You were right, thanks!. The way to solve it is slightly different, though. In ``score()``, we need to pass:
- ``metric="missing"``
- ``metric_special="empirical"``.
- ``metric_missing="empirical"``

To guarantee that line:  ``(metric == "indices" and not isinstance(metric_missing, int)) or`` is satisfied.

Nice catch :)

**Comment by guillermo-navas-palencia** [comment]
Could you please make the changes and point to develop instead of the master branch?

**Comment by isokaze04** [comment]
Actually i am not sure how to change accordingly. You may go ahead to change it. :)

**Comment by guillermo-navas-palencia** [comment]
Done. I close the PR. Thanks!

**Pull request closed without merging**
