### PR TITLE
fix metric_missing=0 is ignored in Scorecard._fit #226

### PR DESCRIPTION
**Pull request by peterpanmj**
Very simple fix for a very troublesome bug.

### CODE REVIEW

**Comment by guillermo-navas-palencia** [comment]
Hi @peterpanmj.

Thanks for the bugfix and PR. Could you please create PR to the develop branch instead of master?

**Comment by peterpanmj** [comment]
> Hi @peterpanmj.
> 
> Thanks for the bugfix and PR. Could you please create PR to the develop branch instead of master?

Ok. It is done.

**Comment by guillermo-navas-palencia** [comment]
The tests are failing due to the following:

- your develop branch is not up to date.
- test_missing_metrics is failing. I prefer to avoid random data generation in test functions. Also, consider using pytest.approx().

image

**Comment by guillermo-navas-palencia** [comment]
Thanks @peterpanmj. I agree, I will work on the contribution guide.

**Comment by peterpanmj** [comment]
> The tests are failing due to the following:
> 
> * your develop branch is not up to date.
> * test_missing_metrics is failing. I prefer to avoid random data generation in test functions. Als

> Thanks @peterpanmj. I agree, I will work on the contribution guide.

Just fixed it. I can also help on the contribution guide later.

**Pull request merged**
