### PR TITLE
Allow numpy 2.0+ and fix deprecation warnings

### PR DESCRIPTION
**Pull request by jmahlik**
May want to merge https://github.com/guillermo-navas-palencia/optbinning/pull/335 first to get more test coverage.

I've divided each fix out into a separate commit to show the specific deprecation warning it is fixing. They are fairly minor things but should keep the package healthy for a good while. They'll start raising errors soon. Figured it was best to get them handled before.

Also, added the `ecsos` extra for users who need it since cvxpy no longer will install it [link](https://www.cvxpy.org/updates/index.html#ecos-deprecation).

Let me know thoughts or if you'd like any changes.

### CODE REVIEW

**Review by guillermo-navas-palencia — APPROVED** [review]
It looks good. Thanks for your contribution.

**Comment by jmahlik** [comment]
I wonder if not running the tests on 3.7 and 3.8 might be course of action? So don't drop support entirely via the package metadata (pip would refuse to install it then), but don't explicitly support 3.7 and 3.8 going forward? Anyone using those versions is bound to encounter problems with the C extensions at some point.

The 3.7 and 3.8 tests are building older versions of cvxpy so the tests are failing on those versions with the updates.

It looks like `scs` doesn't release wheels for 3.7: https://pypi.org/project/scs/3.2.7/#files. I could try to get it to build on 3.7 but it might be pretty difficult to maintain a build of scs in this repo.

* Looks like the [build](https://github.com/bodono/scs-python/blob/60972e436229b5324e861b994c1f9272aa4aceaa/.github/workflows/build.yml#L53-L140) uses conda to get the c dependeneis
* Then it runs this [setup script](https://github.com/bodono/scs-python/blob/master/legacy_setup.py) for python 3.8

**Comment by guillermo-navas-palencia** [comment]
I agree, excluding Python 3.7 and 3.8 seems the most sensible option.

**Review by guillermo-navas-palencia — APPROVED** [review]

**Comment by jmahlik** [comment]
I removed 3.7 and 3.8 from the ci and the package classifiers. The package can still install on 3.7 and 3.8 since the `python_requires=>3.7`. The only version I couldn't test locally was 3.9 since I didn't have a 3.9 build laying around. Should be ok in ci though.

**Pull request merged**
