### PR TITLE
Read/save bins Issue #96

### PR DESCRIPTION
**Pull request by alexliap**
This PR aims to resolve Issue #96 by adding to class methods to OptimalBinning object, to_json & read_json.
Continuous and Multiclass binning inherit from that class, so no other methods were needed.
The to_json method also saves the transformation of the training data as requested in the Issue.

### CODE REVIEW

**Comment by alexliap** [comment]
Thank you for the response.
I will work on it, but could you be a little more specific in order to avoid refactoring again?

**Comment by alexliap** [comment]
What about now, i save all the data required for the binning table, but is this the way you want it to behave? should the self._check_is_fitted() change in order to be able to call self.binning_table instead of self._binning_table ?

**Comment by guillermo-navas-palencia** [comment]
Yes, this looks good to me.  Regarding self._is_fitted, yes, I think it should be set to True when reading from JSON.

**Comment by guillermo-navas-palencia** [comment]
To complete the PR, it would be nice to have unit tests for all binning classes :)

**Comment by alexliap** [comment]
Yes of course, I'm on it

**Comment by alexliap** [comment]
uuum question, why MulticlassOptBinning doesn't require dtype of variable as input?

**Comment by guillermo-navas-palencia** [comment]
> uuum question, why MulticlassOptBinning doesn't require dtype of variable as input?

MulticlassOptBinning only accepts numerical dtype.

**Review by guillermo-navas-palencia — APPROVED** [review]

**Comment by guillermo-navas-palencia** [comment]
Thanks!

**Pull request merged**
